# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcbb00c6695ba1a6cdbc8b0306d149703401319ba3900e3eda5767df2ae6e445a0ac08ac6c0409db53ac6a1428d47ec164db001f5784c607b6e0e3da3373f392

test:
  secret_key_base: 79749cc8bbe1a679613c51d1d3f57540fbc425bcb1cf9190f76109d2e5bb778532f7300552b9616589fd0d66ebe3f5552f08a2bdcef7dedba315b11e666b7fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
